version 2.1
jobs:
  build:
    docker:
      - image : node:19
    steps:
      - checkout
      - run: echo "Docker image executed"
  tests:
    steps:
      - checkout
      - run: echo "Docker"

workflows:
  minimal:
    jobs:
      - build
      - tests
