version: 2
jobs:
  build:
    docker:
      - image : node:19
    steps:
      - run:
         - command : echo "Docker image executed"
  tests:
    steps:
      - checkout
      - run:
        - command : echo "Docker image executed"

workflows:
  version: 2
  minimal:
    jobs:
      - build
      - tests
